### ISSUE TITLE
should use cdp.CDPParser rather than argparse

### ISSUE THREAD

**Issue by doutriaux1** [E3SM-Project/e3sm_to_cmip#1]
This opens the door to parameter files and unification of arguments accorss project via the `cia` project.

see:
https://github.com/CDAT/cdp
and
https://github.com/PCMDI/CIA

@zshaheen can you point to examples.

**Comment by sterlingbaldwin** [comment]
Can these arguments also be passed via the command line?

**Comment by doutriaux1** [comment]
yep, that's the beauty of it
and you can overwrite the param file via command line
