### ISSUE TITLE
Refactor the API design for `cmor_handlers`

### ISSUE THREAD

**Issue by tomvothecoder** [E3SM-Project/e3sm_to_cmip#103]
Discussion source: https://github.com/E3SM-Project/e3sm_to_cmip/pull/102#issuecomment-1010124839

> > I notice each of these 8 variables have identical handlers. Other than variables that are handled by default handlers, one variable has one handlers. This was a design choice and perhaps easier to follow for other developers but definitely have many code replications..
> 
> Maybe in the future, if we have the bandwidth or additional developer support, we can refactor the handlers so that they extend from a base/parent class (e.g., `class Handler`) with abstract `write_data` and `handle` methods. Each handler file would inherit from this class, and override and/or add methods as needed. It would make managing the code a lot easier by reducing code redundancy, with this PR being a good example. I'll open up an issue for this.

Related issues
* https://github.com/E3SM-Project/e3sm_to_cmip/issues/99

**Comment by chengzhuzhang** [comment]
Sterling mentioned to use Abstract Base Class, which could be one possibility for this PR. https://github.com/E3SM-Project/e3sm_to_cmip/pull/54#issuecomment-668707309
