### ISSUE TITLE
"Error could not convert data to a numpy array" and "Nafs" in cLitter and potentially other land varibles handlers

### ISSUE THREAD

**Issue by chengzhuzhang** [E3SM-Project/e3sm_to_cmip#107]
@TonyB9000 discovered that cLitter cmorization failed with "Error could not convert data to a numpy array". On inpecting cLitter.py, the same fixes for converting to numpy array and fill in NaN values are needed. Potentially other land variable handlers may need both fixes.

**Comment by chengzhuzhang** [comment]
Hey Tom, I'm a little short of hands, would you please take care of this issue? essentially, both problems were caused by moving to xarray. I think you had fixed `not a numpy array problem` for `lai` and `trans`, but they should also have the `Nafs` problem. Would you go around the land variable list to fix any handles have this issue? Variable 1-12 in this table:https://acme-climate.atlassian.net/wiki/spaces/DOC/pages/925500501/Lmon+variable+conversion+table. Default handlers (variable only need units conversion) has already taken care of. Let me know if you'd like any clarification. Thanks!

**Comment by tomvothecoder** [comment]
@chengzhuzhang Got it, I should be able to have a PR ready soon.
