### ISSUE TITLE
Refactor `phalf.py` and `pfull.py` to `handlers.yaml`

### ISSUE THREAD

**Issue by tomvothecoder** [E3SM-Project/e3sm_to_cmip#115]
## Handlers to Refactor
 
Handlers that use CDAT -- uses `cdutil.vertical.reconstructPressureFromHybrid` (not in xarray natively)
- pfull.py
- phalf.py

### Other Info
For local package builds using `pip install .` or `python setup install`, the `setup.py` file is used.
The `install_requires` section of `setup.py` is supposed to list the required dependencies for the package that can be installed via pip (it doesn't have this section right now). This is most likely because `cdms2` and `cdutil` are only hosted on Anaconda and not pip. Therefore, building the local package using either command would result in these two dependencies to be missing the Conda environment.

Related lines:
- https://github.com/E3SM-Project/e3sm_to_cmip/blob/684416f69425ef52f6ec9c94203bbb5798d20c53/conda-env/dev.yml#L19-L22
- https://github.com/E3SM-Project/e3sm_to_cmip/blob/684416f69425ef52f6ec9c94203bbb5798d20c53/e3sm_to_cmip/cmor_handlers/pfull.py#L12-L17
- https://github.com/E3SM-Project/e3sm_to_cmip/blob/684416f69425ef52f6ec9c94203bbb5798d20c53/e3sm_to_cmip/cmor_handlers/phalf.py#L12-L17

**Comment by xylar** [comment]
@tomvothecoder, I think it would be great if `e3sm_to_cmip` could be available on pypi and not just conda-forge.

I wanted to caution that it's not generally a good idea to get dependencies for a conda environment from pypi unless you're careful to get *all* of them from pypi.  So in my experience doing `pip install .` into a conda environment without first carefully installing the dependencies from `conda-forge` can get you in some pretty serious trouble.

In my view, the workflow for anyone wanting to to `pip install .` (or better yet `python -m pip install -e .`) would be to first install all of the dependencies from `conda-forge` with something like:
```
mamba create -y -n dev_e3sm_to_cmip --file dev_spec.txt
conda activate dev_e3sm_to_cmip
python -m pip install -e .
```
The `dev_spec.txt` would be similar (but preferable in my view) to the yaml files you currently use for development environments.

Perhaps we can find time to discuss this further in a meeting sometime?

**Comment by tomvothecoder** [comment]
Thanks for the information. @xylar  Yup, the workflow you mentioned with installing conda-forge dependencies first is what we do now in this repo.

This specific issue was raised because some developers on the https://github.com/E3SM-Project/esgfpub repo would install the latest master version of `e3sm_to_cmip` using `python setup.py install` or `pip install .` into `esgfpub` related envs. However, this causes missing dependencies since `e3sm_to_cmip`'s `setup.py` file doesn't list them.

I noticed you opened up an issue from e3sm_diags awhile back describing the `.txt` file approach over the `.yml` approach: https://github.com/E3SM-Project/e3sm_diags/issues/471

> Additionally, you can specify more than one file, which can be useful if you are simultaneously developing more than one project in the same development environment (e.g. output_viewer or cdms2) as long as the other project also has a dev-spec.txt file for its requirements. 

Your approach with using the `dev_spec.txt` seems to open up the possibility of using multiple env spec files to create a single environment, which we seem like we need for esgfpub. I'll look more into this to see if it meets our requirements.

> Perhaps we can find time to discuss this further in a meeting sometime?

Sounds good with me, we can discuss further at one of the Friday meetings with Jill and Ryan soon.

**Comment by tomvothecoder** [comment]
I actually found this related to creating an env using multiple .yml files:

https://github.com/conda/conda/issues/5821#issuecomment-651959113

> conda create allows multiple --file specifications, as long as name: <name> is not present in any of them. conda env create only allows one --file specification, which may or may not have name: <name> present.
> 
> One complaint I have had for a long time is that conda has two methods for creating an environment and they each behave differently; I always forget which one behaves which way and its very frustrating. I think that there should only be one method for creating an environment, and it should accept multiple --file specifications.
> Files should combine as follows:
> 
>     package names unioned, e.g. pkg1 pkg2 + pkg2 pkg3 -> pkg1 pkg2 pkg3
>     package versions intersected, e.g. pkg > 1.0 + pkg < 2.0 -> pkg >1.0,<2.0
>     incompatible intersections raise error or first encounter given precedence
>     The first name: <name> encountered should be given precedence
>     The option -n <name> should be given precedence over any file spec

**Comment by xylar** [comment]
> This specific issue was raised because some developers on the https://github.com/E3SM-Project/esgfpub repo would install the latest master version of `e3sm_to_cmip` using `python setup.py install` or `pip install .` into `esgfpub` related envs. However, this causes missing dependencies since `e3sm_to_cmip`'s `setup.py` file doesn't list them.

I think it's legit to just say that your package doesn't support these methods of installation.  That's the case for all of the conda packages I develop.  You have to get them (or their dependencies) from conda-forge.  But that clearly restricts which workflows they can be incorporated into.  So I support the idea of putting `e3sm_to_cmip` on pypi if possible and supporting installation with pip for sure.
