### ISSUE TITLE
parallel mode seems broken

### ISSUE THREAD

**Issue by xylar** [E3SM-Project/e3sm_to_cmip#13]
...but serial mode seems to be working.

In parallel mode:
https://github.com/E3SM-Project/e3sm_to_cmip/blob/master/e3sm_to_cmip/lib.py#L35
```
    for idx, handler in enumerate(handlers):
```
I'm seeing:
```
idx = 0
handler = {u'name': u'pbo', u'raw_variables': ['MPASO', 'MPASO_namelist', 'MPAS_mesh', 'MPAS_map', 'PSL'], u'positive': None, u'units': 'Pa', u'table': 'CMIP6_Omon.json', u'method': <function handle at 0x2ab9ae326668>}
```
Looks good!

The next line:
https://github.com/E3SM-Project/e3sm_to_cmip/blob/master/e3sm_to_cmip/lib.py#L36
```
        for _, handler_info in handler.items():
```
doesn't really make sense.  This is iterating through the values of the handler, which aren't the kind of thing you would iterate through.  Legacy code?

I think this needs to be updated to look more like the equivalent in serial:
https://github.com/E3SM-Project/e3sm_to_cmip/blob/master/e3sm_to_cmip/lib.py#L105-L119

**Comment by xylar** [comment]
I'm going to see if I can fix this because testing in serial mode will be really slow...

**Comment by sterlingbaldwin** [comment]
I think I tweaked the way the run_serial worked and didnt update run_parallel. This should be an easy fix.
