### ISSUE TITLE
New variable request: converter for monthly averaged daily max/min temperature

### ISSUE THREAD

**Issue by chengzhuzhang** [E3SM-Project/e3sm_to_cmip#139]
E3SM v2 starts to output monthly averaged daily max/min temperature (tasmax/tasmin, CMIP names)
TREFMXAV, TREFMNAV (E3SM name) as standard output. 

There are handlers existing for tasmax and tasmin (sub-monthly), need to support additional handler for both variables.

**Comment by chengzhuzhang** [comment]
Hey @tomvothecoder just to bring this issue into your attention. We can include it as a use case to consider for the revamp plan.

**Comment by tomvothecoder** [comment]
I linked this issue to the PR that is in progress

**Comment by chengzhuzhang** [comment]
That's great. Thank you!
