### ISSUE TITLE
mpaso variable wo axis issue

### ISSUE THREAD

**Issue by sterlingbaldwin** [E3SM-Project/e3sm_to_cmip#16]
The wo handler when run gives the following message:

```
Error: You defined variable 'wo' (table Omon) with axis id 'depth_coord_half', the variable calls for a generic axis of type 'olevel' according to your table, the axis you are providing is of generic type 'olevhalf'
```

@xylar Im not sure if the axis can just be swapped over to olevel instead of olevhalf without messing up the data.

**Comment by xylar** [comment]
No, it really needs to be olevhalf.  I had a lot of trouble with that one.  I can look at it eventually but I'm on leave for 2 weeks now so it won't be soon.

**Comment by xylar** [comment]
This worked when I tested so it's annoying that it stopped working in the meantime.  but the table for half z levels was pretty messed up before (things weren't defined in a consistent way like for the full z levels).  Maybe it's been fixed in the meantime and broke the code in the process.
