### ISSUE TITLE
Consider moving `cwl_workflows` from the repo to `datasm`

### ISSUE THREAD

**Issue by tomvothecoder** [E3SM-Project/e3sm_to_cmip#162]
@TonyB9000 That is a good discussion item for our next E3SM Publication Meeting, which I think is after Thanksgiving.

I sent an email on 7/21/22 that lists our options.

I am leaning towards the second option. This will keep the `cwl_workflows` version controlled alongside `datasm`, which makes the most sense (since `e3sm_to_cmip` is a standalone package).

Options | Keeping CWL workflows in the `e3sm_to_cmip` repo and bundling it in the Python package | Hosting the CWL workflows under DataSM | Hosting them in another “independent dependency” with their own git repo and conda-forge package
-- | -- | -- | --
Pros | The CWL workflows can be distributed to a broader audience by bundling the directory with the `e3sm_to_cmip` package (which has other users)Faster development and debugging cycles for the CWL workflows, since we can test local builds of `e3sm_to_cmip` with the workflows directly before merging the changes to the master branch | The CWL workflows are needed in DataSM, makes it easier to work with the CWL workflows in DataSM since it is in the same repo | Modularity with dependencies CWL workflows can be released as a data package on conda-forge, which makes them available to a broader audience
Cons | CWL workflows are technically a separate tool that depends on `e3sm_to_cmip`, so it isn’t modular to keep it in the `e3sm_to_cmip` repoCWL workflows probably aren’t being used by others outside of the E3SM Publication team right now since it requires cloning the repo or downloading the CWL workflows directory to use them | Limits distribution of the package to DataSM – the CWL workflows were never included in the `e3sm_to_cmip` Anaconda package, so I don’t think people actually used them unless they cloned the repo. | Increases development overhead because we have to manage a separate repository and package release process, then update the dependency version in other tools like DataSM  – probably not an issue if we don’t expect the CWL workflows to be updated that much
When this makes sense | If we want to keep the CWL workflows coupled with the `e3sm_to_cmip` package for ease of development, debugging, and distribution | CWL workflows are only really used by the E3SM Publication team. The CWL workflows are used only with the latest release of e3sm_to_cmip on conda-forge | The CWL workflows are considered a tool that isn’t coupled with any repository, since it depends on `e3sm_to_cmip`We intend on releasing the CWL workflows as a data package on conda-forge. We can call it `cmor_cwl_workflows` as Tony suggested, and it can be listed under the dependencies for DataSM.

**Comment by TonyB9000** [comment]
Option 2 is fine with me.  I had always assumed that E2C releases included those cwl workflows, hence moving them under datasm would make them unavailable to those for whom E2C is accessible.

BTW, I was wrong to call it "cmor_cwl_workflows" because some of them support E3SM climo and time-series generation, has nothing to do with e2c or cmorizing.  I recommend "e3sm_cwl_workflows" if detached, else just "cwl_workflows" under datasm.

I intend to change the "staging/resource/cmor/cwl_workflows install location to eliminate the "cmor", eventually.

**Comment by TonyB9000** [comment]
Also, great breakdown of options and pros and cons!

**Comment by tomvothecoder** [comment]
@TonyB9000 will move cwl workflows to `datasm` (option #2).
