### ISSUE TITLE
e2c v1.10.0rc1 with cmor 3.7.2 environment fails to build

### ISSUE THREAD

**Issue by TonyB9000** [E3SM-Project/e3sm_to_cmip#197]
Upping the e2c/conda-env/dev.yml to cmor 3.7.2 generates the terminal error:

> Encountered problems while solving:
>   - package cdms2-3.1.5-py310h65abc81_13 requires python >=3.10,<3.11.0a0 *_cpython, but none of the providers can be installed
>

**Comment by xylar** [comment]
@TonyB9000 and @tomvothecoder, I think the very restrictive pins in `conda-env/dev.yml` mean that several packages will need to be updated in tandem for things to remain compatible.  My suggestion would be to make a new environment with just the looser  constraints in `conda-env/ci.yml` (except `cmor=3.7.1` in #196 or `3.7.2` here) and use the resulting environment to determine new pins for `dev.yml` if you are wanting to update it.

I am quite sure the pins in `dev.yaml` are related to this issue here and I think they could also be related to the issue in #196, though that's less obvious.

**Comment by TonyB9000** [comment]
I would be happy to be "trained" on this procedure.  At the moment I have background jobs running that will take days.
I'll try ci.dev, with cmor=3.7.2 (latest) just to see if I can get as far as "e2c --version".  I assume one needs to capture the resulting conda negotiations in order to craft an updated dev.yml.

**Comment by TonyB9000** [comment]
I built env "ci_e2c_1100_cmor372" using ci.dev w/cmor 3.7.2, and pip installed e2c (e3sm_to_cmip) 1.10.0rc1.
Conda output captured (in ci_w_cmor327_build_output) - all looks clean.

e3sm_to_cmip --version says:

> 
> Traceback (most recent call last):
>   File "/home/bartoletti1/mambaforge/envs/ci_e2c_1100_cmor372/bin/e3sm_to_cmip", line 5, in <module>
>     from e3sm_to_cmip.__main__ import main
>   File "/home/bartoletti1/mambaforge/envs/ci_e2c_1100_cmor372/lib/python3.10/site-packages/e3sm_to_cmip/__main__.py", line 48, in <module>
>     np.warnings.filterwarnings("ignore")  # type: ignore
>   File "/home/bartoletti1/mambaforge/envs/ci_e2c_1100_cmor372/lib/python3.10/site-packages/numpy/__init__.py", line 322, in __getattr__
>     raise AttributeError("module {!r} has no attribute "
> AttributeError: module 'numpy' has no attribute 'warnings'. Did you mean: 'hanning'?

Conda used numpy 1.25.1 if that helps...

**Comment by tomvothecoder** [comment]
@TonyB9000, I sent you an email on 7/10 ("RE: Question in Dependency Logic") after our 7/10 E3SM Pub team meeting with some info on simplifying the conda environments.

> 1. Go through conda-env yaml dependencies and only keep the ones referenced directly in datasm  (e.g., remove cmor=3.7.0)
> 2. Simplify the conda-env yaml files
>    - Replace static pins (e.g., python=3.10.10) with loose constraints where needed (e.g., python >=3.9)
>    - Refer to this [e3sm_diags](https://github.com/E3SM-Project/e3sm_diags/pull/696) PR for why we should do this and how to do this
>

**Comment by TonyB9000** [comment]
I'll do that.  But to avoid the added complications of datasm, I want to build a pure "e3sm_to_cmip" environment to run e2c "straight out of the box", and it will not accept/run e2c 1.10.0rc1.  Should I follow the same procedure with e2c dev.yml?  I would like to use the latest cmor (3.7.2) as suggested by Paul Durack.  E2c uses cmor directly, etc.

I'll read through the https://github.com/E3SM-Project/e3sm_diags/pull/696 PR.  Thanks.

**Comment by tomvothecoder** [comment]
> @TonyB9000, I sent you an email on 7/10 ("RE: Question in Dependency Logic") after our 7/10 E3SM Pub team meeting with some info on simplifying the conda environments.
> 
> > 1. Go through conda-env yaml dependencies and only keep the ones referenced directly in datasm  (e.g., remove cmor=3.7.0)
> > 2. Simplify the conda-env yaml files
> >    
> >    * Replace static pins (e.g., python=3.10.10) with loose constraints where needed (e.g., python >=3.9)
> >    * Refer to this [e3sm_diags](https://github.com/E3SM-Project/e3sm_diags/pull/696) PR for why we should do this and how to do this

Sorry I got this repo confused with datasm (we just need to do #2). I'll work on this task for this repo which might fix this issue.

**Comment by TonyB9000** [comment]
OK - I'll scour datasm meanwhile to eliminate "indirect dependencies" (e.g. cmor).

**Comment by tomvothecoder** [comment]
Just an FYI, I created a conda environment with `e3sm_to_cmip=1.10.0rc1` and it picks up `cmor=3.7.2` implicitly through the Anaconda [meta.yaml](https://github.com/conda-forge/e3sm_to_cmip-feedstock/blob/dev/recipe/meta.yaml) recipe (which has loose constraints). 

```bash
$ conda create -n e2c_test
$ conda activate e2c_test
$ conda install -c "conda-forge/label/e3sm_to_cmip_dev" e3sm_to_cmip
```
```bash
$ conda list
....
cmor                      3.7.2           py310hd9cea1f_1    conda-forge
```

If we update this repo's `dev.yml` and `ci.yml` with loose constraints, it should mimic the behavior of the Anaconda recipe.

**Comment by TonyB9000** [comment]
I'll try that in my e3sm_to_cmip repo. (I assume I can use the channel listed in the yml and not specify on command line).  If it builds an e2c environment (with cmor 3.7.2) I pip install e3sm_to_cmip 1.10.0rc1 and test "--info" modes.
