### ISSUE TITLE
Add flexibility for additional sampling frequencies

### ISSUE THREAD

**Issue by beharrop** [E3SM-Project/e3sm_to_cmip#26]
@sterlingbaldwin, it would be great to include logic to allow sampling frequencies beyond monthly to be processed.  The two things I think that need to change would be some logic to specify which table to read in (e.g., CMIP6_Amon.json, CMIP6_day.json, CMIP6_E1hr.json), and a modification to the find_atm_files method allowing for different filenames associated with those different sampling frequencies.  Perhaps the easiest thing to do would be to add a flag in the filename to specify different sampling frequencies like VAR_YYYYMM_YYYYMM_FREQ.nc, where FREQ is ('day', '6hr', '6hrPlev', '1hr', etc.).  Alternatively, I suppose, the files could all have the same name and one could use a directory structure to keep them separated.

**Comment by sterlingbaldwin** [comment]
@beharrop daily frequency has been implemented and tested. Other frequencies should also work, but havent been extensively tested, and I havent made CWL workflows for them yet, but I've run a couple quick samples and they're working.
