### ISSUE TITLE
python 3 support (once `cmor` supports python 3)

### ISSUE THREAD

**Issue by xylar** [E3SM-Project/e3sm_to_cmip#5]
This is one of a few packages keeping E3SM-Unified from fully supporting python 3.

**Comment by sterlingbaldwin** [comment]
I tested with the new py3 cmor, and e3sm_to_cmip works fine. I just need to merge everything and do a new build.

**Comment by xylar** [comment]
Do you know if your latest changes mean that we now support python 3 here?  I'm doing my testing in python 2.7 still but would happily switch to python 3 if so.
