### ISSUE TITLE
Variable names need to be comma and space separated

### ISSUE THREAD

**Issue by golaz** [E3SM-Project/e3sm_to_cmip#51]
This may be a minor bug (unless it is a desired feature for some reason that I don't understand)

`e3sm_to_cmip -v rsdt, rsus [...]`

works, but

`e3sm_to_cmip -v rsdt,rsus [...]`

doesn't.

**Comment by sterlingbaldwin** [comment]
Thats just how argparse handles lists of values for an argument. Note that the usage messages states "space separated list of variables."

**Comment by golaz** [comment]
Yes, it's a bit of a strange feature. To get around it, I usually get the argument as a string then parse it myself.
