### ISSUE TITLE
Axis valid_min error

### ISSUE THREAD

**Issue by mnichol3** [E3SM-Project/e3sm_to_cmip#52]
When attempting to CMORize some CAM5 output to create `drybc`, I keep getting the following error:
```
Error: axis latitude (table: AERmon), detected value at: -90.947368 when
valid_min is -90.000000
```

I've checked the latitude values in the files being read by the variable handler script (`bc_a1DDF_199901_201412.nc`, `bc_a4DDF_199901_201412.nc`, `bc_c1DDF_199901_201412.nc`, `bc_c4DDF_199901_201412.nc`) and the minimum value in each array is `-90.0`. 

Is there something else that could be causing this error?

Thank you!

**Comment by chengzhuzhang** [comment]
This error doesn't look familiar. Not sure if it is an data issue. Will re-open if it re-occur.
