### ISSUE TITLE
Missing areacello

### ISSUE THREAD

**Issue by xylar** [E3SM-Project/e3sm_to_cmip#60]
The following issue was received by @vanroekel:
> To include CMIP6 models participating in ScenarioMIP in the regional sea-level projections for IPCC AR6, Chapter 9: Oceans, Cryosphere and Sea-Level Change, we need both the regional sea level output ‘zos’ as well as the ocean area weights (‘areacello’) corresponding to the grid at which ‘zos’ is provided. For one or more instances of the grid and model variants of the the ‘zos’ data that your institute has uploaded to ESGF, we were not able to find the corresponding ‘areacello’ data (please see list below). We kindly ask if you could please provide us with this additional data and make it available through ESGF, so that we can incorporate your model simulations in our projections.

I don't recall `areacello` (or `volcello`) coming up during our discussions of which handlers were needed.  They are listed as "cell_measures" on many variables:
```
"cell_measures": "area: areacello volume: volcello",
```

In the OMIP paper:
> In order to calculate ocean area integrals and volume integrals, information is needed to weight the grid cells in a manner consistent with conservation properties of the model. All CMIP6 ocean models have a fixed horizontal grid and hence constant horizontal cell areas. Cell areas (areacello) should be stored in each data file (Table G1) in order to keep this important information within each diagnostic file.

So it looks like we need to compute this and add it to all ocean variables that are weighted by `areaCell`.

I'm not at all clear on how this should be handled.  How will we update existing published data sets?  How will we add this to appropriate variables going forward?

Do we need to add related variables `volcello` and `thkcello`?

Here is a draft handler:
``` python
"""
compute  Grid-Cell Area for Ocean Variables areacello
"""
from __future__ import absolute_import, division, print_function

import xarray
import logging

from e3sm_to_cmip import mpas
from e3sm_to_cmip.util import print_message

# 'MPAS' as a placeholder for raw variables needed
RAW_VARIABLES = [''MPAS_mesh', 'MPAS_map']

# output variable name
VAR_NAME = 'areacello'
VAR_UNITS = 'm2'
TABLE = 'CMIP6_Ofx.json'


def handle(infiles, tables, user_input_path, **kwargs):
    """
    Transform MPASO cellArea into CMIP.areacello
    Parameters
    ----------
    infiles : dict
        a dictionary with namelist, mesh and time series file names
    tables : str
        path to CMOR tables
    user_input_path : str
        path to user input json file
    Returns
    -------
    varname : str
        the name of the processed variable after processing is complete
    """
    if kwargs.get('simple'):
        msg = f"{VAR_NAME} is not supported for simple conversion"
        print_message(msg)
        return
        
    msg = 'Starting {name}'.format(name=__name__)
    logging.info(msg)

    meshFileName = infiles['MPAS_mesh']
    mappingFileName = infiles['MPAS_map']

    dsMesh = xarray.open_dataset(meshFileName, mask_and_scale=False)
    cellMask2D, _ = mpas.get_cell_masks(dsMesh)
    areaCell = dsMesh.areaCell.where(cellMask2D)

    ds = xarray.Dataset()
    ds[VAR_NAME] = areaCell
    ds = mpas.remap(ds, mappingFileName)

    mpas.setup_cmor(VAR_NAME, tables, user_input_path, component='ocean')

    # create axes
    axes = [{'table_entry': 'latitude',
             'units': 'degrees_north',
             'coord_vals': ds.lat.values,
             'cell_bounds': ds.lat_bnds.values},
            {'table_entry': 'longitude',
             'units': 'degrees_east',
             'coord_vals': ds.lon.values,
             'cell_bounds': ds.lon_bnds.values}]
    try:
        mpas.write_cmor(axes, ds, VAR_NAME, VAR_UNITS)
    except Exception:
        return ""
    return VAR_NAME
```

**Comment by xylar** [comment]
@sterlingbaldwin, @chengzhuzhang, @rljacob, your input would be appreciated.  How is the corresponding atmosphere cell area currently handled?

**Comment by chengzhuzhang** [comment]
@xylar We have similar auxiliary variables (fixed with time) for atmosphere: https://acme-climate.atlassian.net/wiki/spaces/ED/pages/1010402171/fx+variable+conversion+table
these variables are published individually along with each simulations. @sterlingbaldwin just recently republished one of these variables for atmosphere. It seems `areacello` and `thkcello` should be handled similarly as these atmospheric variables.

**Comment by sterlingbaldwin** [comment]
The corresponding atmos variable `areacella` isn't added to each of the atmos variables, instead its supplied separately as its own dataset for each experiment since its a constant. I think we could do the same thing here, I dont think we would need to go back and update every ocean variable with the constant value. With this new handler, I can fairly easily add the new variables to each of the experiments (I had to do this recently with a different variable, so 90% of the setup is already done).

I think we (probably me actually) should go and make sure that for every variable we publish, anything listed in the `cell_measures` is also published along side.

**Comment by sterlingbaldwin** [comment]
I just checked the `cell_measures` for all our variables, the only ones missing are `areacello` and `volcello`. I also saw `"cell_measures": "--OPT"` for a few but these are ignored by PrePare and CMOR and substituted for an empty string so can be ignored.

**Comment by xylar** [comment]
Okay, I'm relieved to know that this isn't quite as big a deal as I thought.

**Comment by xylar** [comment]
`thkcello` should be a very simple modification of https://github.com/E3SM-Project/e3sm_to_cmip/blob/master/e3sm_to_cmip/cmor_handlers/masscello.py, where we just don't multiply by `config_density0` (and obviously the units change).  And `volcello` would just be the same but multiplied by `areaCell`.  I should have a PR for all 3 by tomorrow.
