### ISSUE TITLE
e3sm_to_cmip for daily data

### ISSUE THREAD

**Issue by ypeings** [E3SM-Project/e3sm_to_cmip#66]
Dear all,

I have successfully converted monthly data from our PAMIP (Polar Amplification MIP) E3SM simulations using e3sm_to_cmip (thanks to @czender and his upgrade of ncclimo), so it can be shared on ESGF. 

I know need to take care of the daily data, but I cannot find instructions on how to use the e3sm_to_cmip for daily data. Could somebody help me with this ? Our runs are 14-month runs, going from April 1st to May 31st of the next year, with 100 ensembles or more per experiment. There are only 4 variables I want to convert to CMIP format at the daily frequency (pr,psl,tasmin,tasmax).

Thanks,
Yannick

**Comment by chengzhuzhang** [comment]
I recall that @sterlingbaldwin has added capability to support high frequency data in a most recent release. @sterlingbaldwin would you provide the instruction as well? Thanks.

**Comment by sterlingbaldwin** [comment]
The only difference between monthly vs daily processing is the `--freq=day` flag that needs to be passed. Other then that, its exactly the same, just point the input path at a directory filled with time-series file extracted from the daily files. If you're using the CWL processing scripts, there's a workflow setup to do daily files: https://github.com/E3SM-Project/e3sm_to_cmip/tree/master/scripts/cwl_workflows/atm-day

If you're not using the CWL method, then just extract the time-series files using ncclimo, using the flag `--clm_md=hgh_frq_spl` for the "high-frequency splitter" option.

**Comment by ypeings** [comment]
Thanks @chengzhuzhang and @sterlingbaldwin , I will give it a try !

**Comment by sterlingbaldwin** [comment]
Let me know if it works for you, there have only been a couple usages of it so far and if you run into any problems (or it works perfectly) it would be great to hear about it!

**Comment by ypeings** [comment]
So I've been working on this, I'm struggling to get the data in the right format before using e3sm_to_cmip. It's the same problem I had for the monthly data, because our simulations are 14-month runs (April to May of year 2), ncclimo does not handle it well (for daily data, monthly data works after Charlie's update).

@czender : now that you have tweaked ncclimo so it works on non-full year monthly data, would it be hard to have that feature for daily data too ? I'm talking about the --mth_srt and --mth_end flags that allow to do this. 

I understand it's a lot of work, and if one of you knows an easy workaround let me know. I don't know anything about the CWL processing scripts, maybe I should try that too.

Thanks a lot

**Comment by czender** [comment]
I had a feeling this would end up in my lap :) I would be happy to address this issue as I think it is one that many users might ultimately benefit from. However, this work would pre-empt my efforts (which have not yet started due to previous pre-emptions) to get `ncremap` to work with MOAB. So I must ask @rljacob and @chengzhuzhang if it is OK to prioritize this instead. If so, please create an epic for it, as I should have asked for the monthly splitter work done in Jan/Feb.

**Comment by rljacob** [comment]
Yes this can be a higher priority.

**Comment by czender** [comment]
Thanks, Rob. @ypeings please point me to a sample 14-month dataset on Cori that I can use for testing and evaluation.

**Comment by ypeings** [comment]
@czender  Here are monthly (h0), daily (h1) and 6-hour (h2) outputs from one of the 14-month run : /global/cscratch1/sd/ypeings/e3sm_scratch/cori-knl/archive/PAMIP-1.1_101/atm/hist

Thanks for doing that !

**Comment by czender** [comment]
I understand that you want the unaltered daily average from h1 files. For the h2 files do you want the raw 6-houly data, or do you want those averaged into daily data first, or what?

**Comment by ypeings** [comment]
Yes that's correct, I need the unaltered daily average from h1 files. I don't need the h2 files. Just thought I would leave them in there in case you want to make tests with that too.

**Comment by czender** [comment]
@ypeings Also I need read permission on that directory and all files

**Comment by ypeings** [comment]
Ok I've changed the permissions, let me know if you have access

**Comment by czender** [comment]
zender@cori09:~$ cd /global/cscratch1/sd/ypeings/e3sm_scratch/cori-knl/archive/PAMIP-1.1_101/atm/hist
-bash: cd: /global/cscratch1/sd/ypeings/e3sm_scratch/cori-knl/archive/PAMIP-1.1_101/atm/hist: Permission denied

**Comment by ypeings** [comment]
Weird, I've added all-users read permissions to the ypeings directory and all subdirectories linking to the files

**Comment by czender** [comment]
No rush, please test the readability with a different user and let me know when you have this solved.

**Comment by ypeings** [comment]
@czender I got help from the NERSC help desk, you should have access now

**Comment by czender** [comment]
Access works now. I'll post again why I have something for you to test.

**Comment by ypeings** [comment]
@czender Thanks Charlie, looking into this, I'll let you know

**Comment by chengzhuzhang** [comment]
@sterlingbaldwin 

> The only difference between monthly vs daily processing is the `--freq=day` flag that needs to be passed. Other then that, its exactly the same, just point the input path at a directory filled with time-series file extracted from the daily files. If you're using the CWL processing scripts, there's a workflow setup to do daily files: https://github.com/E3SM-Project/e3sm_to_cmip/tree/master/scripts/cwl_workflows/atm-day
> 
> If you're not using the CWL method, then just extract the time-series files using ncclimo, using the flag `--clm_md=hgh_frq_spl` for the "high-frequency splitter" option.

Hey Sterling, can you please update the `end-to-end` workflow for including high-frequency capability?

**Comment by ypeings** [comment]
Hi @czender , the updated ncclimo for daily data seems to work, I get the April to May daily timeseries I need for this data. Thank you for your help with this.

I still have problems with e3sm_to_cmip for that daily data though, with a "No handlers loaded" message. I'm trying to figure it out, please let me know if any of you has some recommendations.

**Comment by czender** [comment]
Glad to hear it. I think many people will find this feature useful.

As for the `e3sm_to_cmip`, it may be difficult for them to support this new feature until NCO has another release that can be loaded via Conda. I plan to release 4.9.9 later this month, though that can be accelerated if necessary. @sterlingbaldwin LMK if you need 4.9.9 released sooner than end of this month.

**Comment by sterlingbaldwin** [comment]
@ypeings what variables are you trying to process?

**Comment by ypeings** [comment]
@sterlingbaldwin I'm running a test with psl. ncclimo creates the file PSL_YYY104_YYY205.nc (my runs go from April to May of year +1) in the right directory, but then e3sm_to_cmip gives me the following error : 
[-] No handlers loaded

I run the following command :
e3sm_to_cmip -v psl --freq day --input $DIRIN --output $DIROUT -t ./cmip6-cmor-tables/Tables -u e3sm_user_config_picontrol.json

**Comment by sterlingbaldwin** [comment]
Ah that would explain it. I’ll have to check but I dont think the daily psl handler’s been implemented. Should be quick and easy.

</Sterling Baldwin>

On Apr 6, 2021, at 4:25 PM, ypeings ***@***.***> wrote:

﻿

@sterlingbaldwin<https://urldefense.us/v3/__https://github.com/sterlingbaldwin__;!!G2kpM7uM-TzIFchu!gynVO0wIfBGbGniTSEtF4v9TKFbwHToafr1FB3WGIa1LjA8c4RqcNcnRnSR9J4P5hwo$> I'm running a test with psl. ncclimo creates the file PSL_YYY104_YYY205.nc (my runs go from April to May of year +1) in the right directory, but then e3sm_to_cmip gives me the following error :
[-] No handlers loaded

I run the following command :
e3sm_to_cmip -v psl --freq day --input $DIRIN --output $DIROUT -t ./cmip6-cmor-tables/Tables -u e3sm_user_config_picontrol.json
