### ISSUE TITLE
Add cmor_handlers for ILAMB

### ISSUE THREAD

**Issue by jhkennedy** [E3SM-Project/e3sm_to_cmip#7]
In order to get the full analysis capabilities of ILAMB, these CMOR variables will need to be (available to be) created from E3SM output: 

```
- al || albedo*
- burntArea
- co2
- cSoil* || soilc
- cVeg || biomass*
- ___ || EvapFrac
- evspsbl || et* 
- gpp
- nbp
- ___ || nee*
- ___ || reco*
- hurs || rhums* 
- ___ || rlns*
- ___ || rns*
- ___ || rsns*
- mrro || runoff*  
- snw || swe*
- ___ || twsa* || tws
```
where the first variable indicates the CMIP6 official variable name (`___` for unknown), `||` separates possible (understood by ILAMB) variable names (likely derived from past MIPs), and the `*` indicates the default variable name in ILAMB.

**Comment by sterlingbaldwin** [comment]
I just finished all the atmos variables, and am about to start one the land ones. Assuming I have all the formulas, I should be able to get these all done next week.
