### ISSUE TITLE
Redundant rlut converters

### ISSUE THREAD

**Issue by sterlingbaldwin** [E3SM-Project/e3sm_to_cmip#70]
There are two versions of the rlut converter, one in the default and one explicit. The default one is wrong and should be removed.

**Comment by chengzhuzhang** [comment]
Hey Sterling, would you elaborate on this issue? For Amon table we have a different formula. I thought supporting multiple converter is supported?

**Comment by sterlingbaldwin** [comment]
So it _is_ supported to have multiple converters for the same variable, however they need to have different names. For example there is "pr" and "pr_day" since the formula for daily pr is different. The issue here however is that the manually implemented "rlut" is correct, and the formula for the simple handler is wrong. Should be an easy fix, just remove the simple handler definition. The upside of this bug was that the complex handlers are loaded after the simple ones, so when trying to convert rlut, the incorrect handler was just getting overwritten by the correct one.

**Comment by chengzhuzhang** [comment]
Thanks for the clarification. It sounds like in this particular case, we will just have rlut_daily for the simple handler. It might be useful in the long run, to build an ordered dictionary structure to handle the same variable with different formula situation. An example from e3sm-diags: https://github.com/E3SM-Project/e3sm_diags/blob/462f4c77d01e7fdc3e37c70541f4fb5e826d0406/acme_diags/derivations/acme.py#L497 that might be useful at a later time.

**Comment by sterlingbaldwin** [comment]
I already have some logic to pick the correct CMIP table based on the frequency of the being converted, I could tag the handlers with the frequencies they can convert and then pick the correct one at run time. ``pr_day`` was a quick and easy hack that worked, but perhaps isnt the best long term solution.
