### ISSUE TITLE
Addtional handler for high frequency pr

### ISSUE THREAD

**Issue by chengzhuzhang** [E3SM-Project/e3sm_to_cmip#74]
As brought up by @crterai A handler is needed when precipitation is output as PRECL and PRECC in high frequency

**Comment by chengzhuzhang** [comment]
Hey @sterling, in current work, we have PRECT output at high frequency.
I found:
```
- cmip_name: pr_highfreq
  e3sm_name: PRECT
  units: 'kg m-2 s-1'
  table: CMIP6_day.json
  unit_conversion: 'm/s-to-kg/ms'
```
and the pr handler for PR = PRECT+PRECC for monthly frequency. I'm wondering what is the best way to accommodate this new handler?

**Comment by sterling** [comment]
I think you have the wrong Sterling

**Comment by chengzhuzhang** [comment]
Thank you for pointing out...@sterling

**Comment by chengzhuzhang** [comment]
@sterlingbaldwin any advice on this implementation?

**Comment by sterlingbaldwin** [comment]
hahaha sorry @sterling
