### ISSUE TITLE
Update Anaconda package uploading process

### ISSUE THREAD

**Issue by tomvothecoder** [E3SM-Project/e3sm_to_cmip#92]
Acceptance Criteria
- [x] Update `setup.py` `author` and `author_email` (list of current contributors)
- [x] Remove `meta.yaml` since uploads are now done via the [conda-forge feedstock](https://github.com/conda-forge/e3sm_to_cmip-feedstock)
- [x] Add `tbump` to dev dependences for bumping versions
- [ ] Update docs on releasing

**Comment by xylar** [comment]
@tomvothecoder, more importantly, `e3sm_to_cmip` is on `conda-forge` so we shouldn't be building our own packages for the `e3sm` channel at all anymore.  In fact, I would prefer to delete the one that got uploaded if that's okay.

https://anaconda.org/conda-forge/e3sm_to_cmip/files
https://anaconda.org/e3sm/e3sm_to_cmip/files

Having 2 channels isn't good.  We really need to stick with one.

**Comment by xylar** [comment]
I labeled all builds of `e3sm_to_cmip` on the `e3sm` channel as `broken`.  That way, someone could install them if they really needed to but no one should do so accidentally.
